### ISSUE TITLE
Your website is broken

### ISSUE THREAD

**Issue by dodspringer** [FuelRats/FCMS#183]
When trying to log in and authorize, it loops between this page and the Frontier store:
![Screenshot_2](https://github.com/FuelRats/FCMS/assets/47904110/35f2ce3d-d90a-4dab-8cc4-1d2ea2dff118)

When trying to report this on your website's feedback button, I get this asinine crap:
![Screenshot_3](https://github.com/FuelRats/FCMS/assets/47904110/ea5d6a9e-76bf-49ec-84c6-0e92e14ef8e7)

**Comment by kenneaal** [comment]
OAuth flow with Frontier's services have been verified to be working correctly. According to the logs, you successfully completed OAuth renewal and viewed logged in page views of your carrier on July 2nd, a bit after noon UTC. Most likely, the refresh attempt was originally made with different login credentials than what FCMS expected.

Your 'asinine crap' is due to the web feedback form being disabled due to PI potentially being leaked through the form submissions, so it has been disabled to better comply with GDPR.

Change your tone on your next report please, or it will just get deleted.

**Comment by dodspringer** [comment]
Apologies for my tone, I was duly frustrated.

Also, it's happening again today.
